version: "3.8"

services:

  rabbit-mq:
    image: rabbitmq:3.9-management
    container_name: rabbit-mq
    volumes:
      - ./data/:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - local2
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  producer:
    image: node:14.18.2-alpine3.14
    container_name: producer
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./producer/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
    # ports:
    #   - 3000:3000
    networks:
      - local2

  consumer:
    image: node:14.18.2-alpine3.14
    container_name: consumer
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./consumer/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
    # ports:
    #   - 3001:3001
    networks:
      - local2

  consumer2:
    image: node:14.18.2-alpine3.14
    container_name: consumer2
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./consumer/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
    # ports:
    #   - 3002:3002
    networks:
      - local2

  producer_broadcast:
    image: node:14.18.2-alpine3.14
    container_name: producer_broadcast
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./producer_broadcast/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
    # ports:
    #   - 3000:3000
    networks:
      - local2

  consumer_broadcast:
    image: node:14.18.2-alpine3.14
    container_name: consumer_broadcast
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./consumer_broadcast/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
    # ports:
    #   - 3001:3001
    networks:
      - local2

  consumer_broadcast2:
    image: node:14.18.2-alpine3.14
    container_name: consumer_broadcast2
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./consumer_broadcast/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
    # ports:
    #   - 3002:3002
    networks:
      - local2

  producer_direct:
    image: node:14.18.2-alpine3.14
    container_name: producer_direct
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./producer_direct/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
    # ports:
    #   - 3000:3000
    networks:
      - local2

  consumer_direct:
    image: node:14.18.2-alpine3.14
    container_name: consumer_direct
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./consumer_direct/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
      - BINDING_KEY=bot
    # ports:
    #   - 3001:3001
    networks:
      - local2

  consumer_direct2:
    image: node:14.18.2-alpine3.14
    container_name: consumer_direct2
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./consumer_direct/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
      - BINDING_KEY=others
    # ports:
    #   - 3002:3002
    networks:
      - local2

  producer_topic:
    image: node:14.18.2-alpine3.14
    container_name: producer_topic
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./producer_topic/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
    # ports:
    #   - 3000:3000
    networks:
      - local2

  consumer_topic:
    image: node:14.18.2-alpine3.14
    container_name: consumer_topic
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./consumer_topic/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
      - BINDING_KEY=bot
    # ports:
    #   - 3001:3001
    networks:
      - local2

  consumer_topic2:
    image: node:14.18.2-alpine3.14
    container_name: consumer_topic2
    depends_on:
      rabbit-mq:
        condition: service_healthy
    tty: true
    entrypoint: ["/bin/sh", "/home/node/app/.docker/entrypoint.sh"]
    volumes:
      - ./consumer_topic/:/home/node/app/
    environment:
      - AMQP_CONNECTION=amqp://guest:guest123@rabbit-mq:5672
      - BINDING_KEY=others
    # ports:
    #   - 3002:3002
    networks:
      - local2

networks:
  local2:
    driver: bridge
